name: dropdown_button2
description: Flutter's core Dropdown Button widget with steady dropdown menu and many options you can customize to your needs.
version: 1.6.2
homepage: https://github.com/AhmedLSayed9/dropdown_button2

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
